[project]
name = "pandas-2025"
version = "0.1.0"
description = "Relembrando conceitos de Pandas"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "ruff>=0.11.2",
]
